// <auto-generated/>
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "xUnit discovers test classes via reflection; analyzers cannot see instantiation.", Scope = "module")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "Test classes need not be sealed; suppress to reduce noise.", Scope = "module")]
[assembly: SuppressMessage("xUnit", "xUnit1030:Test methods should not call ConfigureAwait(false)", Justification = "ConfigureAwait(false) usage is acceptable in our tests; parallelism is managed elsewhere.", Scope = "module")]
[assembly: SuppressMessage("Design", "CA1515:Consider making public types internal", Justification = "Public required for xUnit collection definition.", Scope = "type", Target = "~T:GameBot.IntegrationTests.ConfigIsolationDefinition")]
